export const SCENARIOS = [
  { id: "scn_001", region: "US", locale: "en-US", flag: "US", title: "Vehicle Recall Bureau", desc: "Federal Motor Carrier Safety Administration advises a mandatory recall on the subject's primary vehicle.", duration: 184, category: "Bureaucratic" },
  { id: "scn_002", region: "US", locale: "en-US", flag: "US", title: "Tier-3 IT Escalation", desc: "Caller from corporate IT reports anomalous outbound packets on the subject's workstation.", duration: 212, category: "Corporate" },
  { id: "scn_003", region: "US", locale: "en-US", flag: "US", title: "Lost Bichon Frise", desc: "Neighbor four doors down believes their missing dog \u2014 Mr. Crumbs \u2014 is in the subject's backyard.", duration: 96, category: "Domestic" },
  { id: "scn_004", region: "GB", locale: "en-GB", flag: "GB", title: "Council Tax Reassessment", desc: "Borough valuation officer scheduling an urgent property visit for revised banding.", duration: 168, category: "Bureaucratic" },
  { id: "scn_005", region: "GB", locale: "en-GB", flag: "GB", title: "Royal Mail Customs Hold", desc: "Parcel detained at the international mail centre pending an unspecified customs declaration.", duration: 144, category: "Bureaucratic" },
  { id: "scn_006", region: "FR", locale: "fr-FR", flag: "FR", title: "EDF Compteur Linky", desc: "Technicien EDF souhaite confirmer un rendez-vous d'installation du compteur communicant.", duration: 132, category: "Utility" },
  { id: "scn_007", region: "DE", locale: "de-DE", flag: "DE", title: "GEZ Beitragsservice", desc: "Rundfunkbeitrag-Vertreter \u00fcberpr\u00fcft die Anmeldung des Haushalts auf der angegebenen Adresse.", duration: 175, category: "Bureaucratic" },
  { id: "scn_008", region: "JP", locale: "ja-JP", flag: "JP", title: "Konbini Lost & Found", desc: "Lawson clerk has located a wallet with the subject's meishi at the register and requests verification.", duration: 88, category: "Domestic" },
  { id: "scn_009", region: "ES", locale: "es-ES", flag: "ES", title: "Hacienda Notificaci\u00f3n", desc: "Agencia Tributaria solicita confirmaci\u00f3n de domicilio para una notificaci\u00f3n urgente.", duration: 192, category: "Bureaucratic" },
  { id: "scn_010", region: "MX", locale: "es-MX", flag: "MX", title: "CFE Corte de Servicio", desc: "Comisi\u00f3n Federal de Electricidad informa un corte programado por adeudo de tres bimestres.", duration: 156, category: "Utility" },
  { id: "scn_011", region: "BR", locale: "pt-BR", flag: "BR", title: "Receita Federal", desc: "Auditor verifica pend\u00eancia na malha fina referente ao exerc\u00edcio anterior.", duration: 204, category: "Bureaucratic" },
  { id: "scn_012", region: "IT", locale: "it-IT", flag: "IT", title: "Telecom Manutenzione", desc: "Operatore TIM segnala un guasto sulla centralina di zona e propone una verifica in linea.", duration: 122, category: "Utility" },
  { id: "scn_013", region: "NL", locale: "nl-NL", flag: "NL", title: "Postcodeloterij", desc: "Caller informs the subject they reside in a winning postcode for this month's draw.", duration: 110, category: "Absurd" },
  { id: "scn_014", region: "SE", locale: "sv-SE", flag: "SE", title: "Skatteverket", desc: "Handl\u00e4ggare beg\u00e4r kompletterande uppgifter ang\u00e5ende fastighetsdeklarationen.", duration: 188, category: "Bureaucratic" },
  { id: "scn_015", region: "AU", locale: "en-AU", flag: "AU", title: "Magpie Swooping Report", desc: "Local council ranger investigating a magpie incident allegedly involving the subject.", duration: 78, category: "Absurd" },
  { id: "scn_016", region: "CA", locale: "en-CA", flag: "CA", title: "Service Canada SIN", desc: "Caller verifying the subject's Social Insurance Number after \u201ctwo flagged transactions in Quebec.\u201d", duration: 198, category: "Bureaucratic" },
  { id: "scn_017", region: "IN", locale: "hi-IN", flag: "IN", title: "Aadhaar Re-verification", desc: "UIDAI representative scheduling a biometric refresh appointment within forty-eight hours.", duration: 162, category: "Bureaucratic" },
  { id: "scn_018", region: "US", locale: "en-US", flag: "US", title: "Microwave Repair Co.", desc: "Confused technician returning the subject's call about an appliance they never reported.", duration: 102, category: "Absurd" },
  { id: "scn_019", region: "KR", locale: "ko-KR", flag: "KR", title: "Coupang Rocket Refund", desc: "Customer agent confirming an unusually large refund request on the subject's account.", duration: 140, category: "Corporate" },
  { id: "scn_020", region: "US", locale: "en-US", flag: "US", title: "HOA Architectural Review", desc: "Board liaison citing unapproved mailbox modifications, ref. CC&R \u00a7 4.3.", duration: 168, category: "Bureaucratic" },
  { id: "scn_021", region: "IE", locale: "en-IE", flag: "IE", title: "An Post Returned Item", desc: "Sorting office reports an undeliverable parcel with insufficient postage \u20ac1.40 due.", duration: 84, category: "Bureaucratic" },
  { id: "scn_022", region: "ZA", locale: "en-ZA", flag: "ZA", title: "Eskom Load Schedule", desc: "Eskom operator confirming a Stage 6 schedule revision affecting the subject's block.", duration: 116, category: "Utility" },
];

export const LOCALES = [
  { code: "en-US", label: "English (United States)", flag: "US" },
  { code: "en-GB", label: "English (United Kingdom)", flag: "GB" },
  { code: "en-CA", label: "English (Canada)", flag: "CA" },
  { code: "en-AU", label: "English (Australia)", flag: "AU" },
  { code: "en-IE", label: "English (Ireland)", flag: "IE" },
  { code: "en-ZA", label: "English (South Africa)", flag: "ZA" },
  { code: "fr-FR", label: "Fran\u00e7ais (France)", flag: "FR" },
  { code: "fr-CA", label: "Fran\u00e7ais (Canada)", flag: "CA" },
  { code: "de-DE", label: "Deutsch (Deutschland)", flag: "DE" },
  { code: "de-AT", label: "Deutsch (\u00d6sterreich)", flag: "AT" },
  { code: "de-CH", label: "Deutsch (Schweiz)", flag: "CH" },
  { code: "es-ES", label: "Espa\u00f1ol (Espa\u00f1a)", flag: "ES" },
  { code: "es-MX", label: "Espa\u00f1ol (M\u00e9xico)", flag: "MX" },
  { code: "es-AR", label: "Espa\u00f1ol (Argentina)", flag: "AR" },
  { code: "es-CO", label: "Espa\u00f1ol (Colombia)", flag: "CO" },
  { code: "pt-BR", label: "Portugu\u00eas (Brasil)", flag: "BR" },
  { code: "pt-PT", label: "Portugu\u00eas (Portugal)", flag: "PT" },
  { code: "it-IT", label: "Italiano (Italia)", flag: "IT" },
  { code: "nl-NL", label: "Nederlands (Nederland)", flag: "NL" },
  { code: "nl-BE", label: "Nederlands (Belgi\u00eb)", flag: "BE" },
  { code: "sv-SE", label: "Svenska (Sverige)", flag: "SE" },
  { code: "no-NO", label: "Norsk (Norge)", flag: "NO" },
  { code: "da-DK", label: "Dansk (Danmark)", flag: "DK" },
  { code: "fi-FI", label: "Suomi (Suomi)", flag: "FI" },
  { code: "pl-PL", label: "Polski (Polska)", flag: "PL" },
  { code: "cs-CZ", label: "\u010cesky (\u010cesk\u00e1 republika)", flag: "CZ" },
  { code: "sk-SK", label: "Sloven\u010dina (Slovensko)", flag: "SK" },
  { code: "hu-HU", label: "Magyar (Magyarorsz\u00e1g)", flag: "HU" },
  { code: "ro-RO", label: "Rom\u00e2n\u0103 (Rom\u00e2nia)", flag: "RO" },
  { code: "el-GR", label: "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac (\u0395\u03bb\u03bb\u03ac\u03b4\u03b1)", flag: "GR" },
  { code: "tr-TR", label: "T\u00fcrk\u00e7e (T\u00fcrkiye)", flag: "TR" },
  { code: "ru-RU", label: "\u0420\u0443\u0441\u0441\u043a\u0438\u0439 (\u0420\u043e\u0441\u0441\u0438\u044f)", flag: "RU" },
  { code: "uk-UA", label: "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430 (\u0423\u043a\u0440\u0430\u0457\u043d\u0430)", flag: "UA" },
  { code: "ar-SA", label: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629 (\u0627\u0644\u0633\u0639\u0648\u062f\u064a\u0629)", flag: "SA" },
  { code: "he-IL", label: "\u05e2\u05d1\u05e8\u05d9\u05ea (\u05d9\u05e9\u05e8\u05d0\u05dc)", flag: "IL" },
  { code: "hi-IN", label: "\u0939\u093f\u0928\u094d\u0926\u0940 (\u092d\u093e\u0930\u0924)", flag: "IN" },
  { code: "ja-JP", label: "\u65e5\u672c\u8a9e (\u65e5\u672c)", flag: "JP" },
  { code: "ko-KR", label: "\ud55c\uad6d\uc5b4 (\ub300\ud55c\ubbfc\uad6d)", flag: "KR" },
  { code: "zh-CN", label: "\u4e2d\u6587 (\u4e2d\u56fd)", flag: "CN" },
  { code: "zh-TW", label: "\u4e2d\u6587 (\u53f0\u7063)", flag: "TW" },
  { code: "th-TH", label: "\u0e44\u0e17\u0e22 (\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e44\u0e17\u0e22)", flag: "TH" },
  { code: "vi-VN", label: "Ti\u1ebfng Vi\u1ec7t (Vi\u1ec7t Nam)", flag: "VN" },
  { code: "id-ID", label: "Bahasa Indonesia (Indonesia)", flag: "ID" },
];

export const ACTIVITY = [
  { id: "evt_8821", scenario: "Tier-3 IT Escalation", subject: "Marcus Cole", number: "+1 (415) 555\u20110182", locale: "en-US", flag: "US", status: "recorded", duration: 212, started: "2026-05-11T14:22:08Z" },
  { id: "evt_8820", scenario: "Council Tax Reassessment", subject: "Ben Whittaker", number: "+44 20 7946 0124", locale: "en-GB", flag: "GB", status: "recorded", duration: 168, started: "2026-05-11T14:18:43Z" },
  { id: "evt_8819", scenario: "EDF Compteur Linky", subject: "Claire Marais", number: "+33 1 70 18 99 24", locale: "fr-FR", flag: "FR", status: "routing", duration: 0, started: "2026-05-11T14:17:11Z" },
  { id: "evt_8818", scenario: "Vehicle Recall Bureau", subject: "Daniel Ortega", number: "+1 (213) 555\u20110099", locale: "en-US", flag: "US", status: "recorded", duration: 184, started: "2026-05-11T14:09:55Z" },
  { id: "evt_8817", scenario: "Hacienda Notificaci\u00f3n", subject: "Luc\u00eda Romero", number: "+34 911 23 45 67", locale: "es-ES", flag: "ES", status: "failed", duration: 0, started: "2026-05-11T14:03:22Z" },
  { id: "evt_8816", scenario: "Konbini Lost & Found", subject: "Hiro Tanaka", number: "+81 3-6432-9981", locale: "ja-JP", flag: "JP", status: "recorded", duration: 88, started: "2026-05-11T13:58:01Z" },
  { id: "evt_8815", scenario: "GEZ Beitragsservice", subject: "Sven Becker", number: "+49 30 901820", locale: "de-DE", flag: "DE", status: "recorded", duration: 175, started: "2026-05-11T13:47:38Z" },
  { id: "evt_8814", scenario: "Magpie Swooping Report", subject: "Holly Pritchard", number: "+61 2 8000 4419", locale: "en-AU", flag: "AU", status: "recorded", duration: 78, started: "2026-05-11T13:41:12Z" },
];

export const localeToCountry = (code) => {
  const m = /-([A-Z]{2})$/.exec(code);
  return (m ? m[1] : code).toLowerCase();
};

export const localeToLanguage = (code) => code.replace("-", "_");
