version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Helsinki"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    groups:
      routine-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
