export const FINNISH_PRANKS = [
  {
    "order_grey" : 2,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploRuidosVersionAcortada.mp3",
    "order_red" : 2,
    "titulo" : "Äänet asunnossa",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/RuidosFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3581",
    "desc" : "Asunnosta kuuluu ääniä. Soitamme ystävällesi ymmärtääksemme, miksi hänen asunnostaan kuuluvat seksiäänet ovat niin voimakkaita. Aivan kuin Tarzan asuisi siellä!",
    "enabled_green" : true,
    "order" : 1,
    "order_yellow" : 2,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Ruidos.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 2,
    "order_blue" : 2
  },
  {
    "order_grey" : 1,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploPizzaVersionAcortada.mp3",
    "order_red" : 1,
    "titulo" : "Pizzatoimitus",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/PizzaFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3585",
    "desc" : "Sopii kaiken ikäisille. Soitamme ystävällesi ja vaadimme häntä maksamaan pizzasta, jota hän ei tilannut. Maksaako hän?",
    "enabled_green" : true,
    "order" : 2,
    "order_yellow" : 1,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Pizza.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 1,
    "order_blue" : 1
  },
  {
    "order_grey" : 5,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploLuzVersionAcortada.mp3",
    "order_red" : 5,
    "titulo" : "Katkaisemme sähkönne",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/LuzFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3583",
    "desc" : "Sopii kaiken ikäisille. Soitamme ystävällesi, sillä hän on ohittanut sähkömittarinsa ja aiomme katkaista hänen sähkönsä. Jotta asiat toimisivat, hänen on maksettava siitä!",
    "enabled_green" : true,
    "order" : 3,
    "order_yellow" : 5,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Luz.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 5,
    "order_blue" : 5
  },
  {
    "order_grey" : 4,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjMarihuana.mp3",
    "order_red" : 4,
    "titulo" : "Tuoksuu ruoholta!",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/MarihuanaFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3582",
    "desc" : "Sopii kaikenikäisille. Soitamme ystävällesi, koska rappukäytävässä tuoksuu ruoho ja naapurit valittavat siitä... Haluatko kuulla, mitä hän sanoo?",
    "enabled_green" : true,
    "order" : 4,
    "order_yellow" : 4,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Marihuana.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 4,
    "order_blue" : 4
  },
  {
    "order_grey" : 11,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploRRSS.mp3",
    "order_red" : 11,
    "titulo" : "Sosiaalisen Median lukitus!",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/RRSSFinland.jpg",
    "enabled_blue" : true,
    "_id" : "3593",
    "desc" : "Soveltuu kaikenikäisille. Soitamme ystävällesi, koska meidän on suljettava hänen tilinsä sosiaalisessa mediassa epäilyttävän toiminnan vuoksi. Miten hän reagoi?",
    "enabled_green" : true,
    "order" : 5,
    "order_yellow" : 11,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaRRSS.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 11,
    "order_blue" : 11
  },
  {
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/NoviaJUJL.jpg",
    "order_blue" : 3,
    "order_grey" : 3,
    "image_urlpp" : "https://static.appha.es/mdbfs/bromapp/pub/jol/NoviaJUJL.jpg",
    "order_red" : 3,
    "audiofile" : "FIBromaTeroauteroNovia.wav",
    "hits" : 0,
    "_id" : "3602",
    "order_green" : 3,
    "enabled_green" : true,
    "order_yellow" : 3,
    "enabled_blue" : true,
    "enabled" : true,
    "enabled_yellow" : true,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploTeroauteroNovia.mp3",
    "desc" : "Suunnattu miehille. Soitamme ystävällesi kysyäksemme, miksi hän soittaa tyttöystävälleni ... haluaako hän flirttailla hänen kanssaan?",
    "order" : 6,
    "titulo" : "Miksi kutsut tyttöystävääni?",
    "enabled_grey" : true,
    "enabled_red" : true
  },
  {
    "order_grey" : 10,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploPerroVersionAcortada.mp3",
    "order_red" : 10,
    "titulo" : "Koirasi on rasittava!",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/PerroFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3588",
    "desc" : "Kohdistettu koiranomistajille. Naapuri soittaa ystävälle kertoakseen, että hänen koiransa ärsyttää koko naapurustoa. Miten hän vastaa?",
    "enabled_green" : true,
    "order" : 7,
    "order_yellow" : 10,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Perro.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 10,
    "order_blue" : 10
  },
  {
    "order_grey" : 8,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FI_Ejemplo_Colonoscopia.mp3",
    "order_red" : 8,
    "titulo" : "Kolonoskopia",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/ColonoscopiaFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3590",
    "desc" : "Sopii kaikenikäisille. Soitamme klinikalta keskustellaksemme kolonoskopiasta, kunnes taustalta kuuluu pientä meteliä. Mitähän se mahtaa olla?",
    "enabled_green" : true,
    "order" : 8,
    "order_yellow" : 8,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_Colonoscopia.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 8,
    "order_blue" : 8
  },
  {
    "order_grey" : 8,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploCoche.mp3",
    "order_red" : 8,
    "titulo" : "Osuit Autooni",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/CocheFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3589",
    "desc" : "Kohdistettu auton omistajille. Ystäväsi on osunut autoosi ja soitamme hänelle vaatien korvausta. Uskooko hän?",
    "enabled_green" : true,
    "order" : 8,
    "order_yellow" : 8,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaCoche.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 8,
    "order_blue" : 8
  },
  {
    "order_grey" : 8,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploWifiVersionAcortada.mp3",
    "order_red" : 8,
    "titulo" : "Varastat WiFini!",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/WifiFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3587",
    "desc" : "Soveltuu kaiken ikäisille. Naapuri soittaa ystävällesi, ”varkaalle”, ja syyttää tätä WiFi-signaalin varastamisesta. Mikään ei ole ilmaista, kaveri!",
    "enabled_green" : true,
    "order" : 8,
    "order_yellow" : 8,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_WiFi.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 8,
    "order_blue" : 8
  },
  {
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/NovioJU.jpg",
    "order_blue" : 6,
    "order_grey" : 6,
    "image_urlpp" : "https://static.appha.es/mdbfs/bromapp/pub/jol/NovioJU.jpg",
    "order_red" : 6,
    "audiofile" : "FIBromaSannaNovio.wav",
    "hits" : 0,
    "_id" : "3603",
    "order_green" : 6,
    "enabled_green" : true,
    "order_yellow" : 6,
    "enabled_blue" : true,
    "enabled" : true,
    "enabled_yellow" : true,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploSannaNovio.mp3",
    "desc" : "Suunnattu naisille. Soitamme ystävällesi kysyäksemme, miksi hän soittaa poikaystävälleni ... haluaako hän flirttailla tämän kanssa?",
    "order" : 9,
    "titulo" : "Miksi soitat poikaystävälleni?",
    "enabled_grey" : true,
    "enabled_red" : true
  },
  {
    "order_grey" : 9,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploTeroAuteroAlcoholicos.mp3",
    "order_red" : 9,
    "titulo" : "Anonyymit alkoholistit",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/AlcoholicosAnonimosJuasapp.jpg",
    "enabled_blue" : true,
    "_id" : "3605",
    "desc" : "Suunnattu kaikenikäisille. Jos ystäväsi pitää juhlimisesta tai juomisesta, tämä on vitsi!. Kutsumme häntä Anonyymien alkoholistien joukosta.",
    "enabled_green" : true,
    "order" : 10,
    "order_yellow" : 9,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaTeroAuteroAlcoholicos.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 9,
    "order_blue" : 9
  },
  {
    "order_grey" : 7,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjMulta.mp3",
    "order_red" : 7,
    "titulo" : "Ylinopeussakko",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/MultaFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3586",
    "desc" : "Osoitettu autoa ajaville. Soitamme ystävällesi ilmoittaaksemme vakavasta vakuutuspetoksesta. Maksaako hän sakot?",
    "enabled_green" : true,
    "order" : 11,
    "order_yellow" : 7,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FI_-_Broma_-_Multa.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 7,
    "order_blue" : 7
  },
  {
    "order_grey" : 12,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploTaxi.mp3",
    "order_red" : 12,
    "titulo" : "Taksisi odottaa",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/TaxiJuasappFIN.jpg",
    "enabled_blue" : true,
    "_id" : "3591",
    "desc" : "Sopii kaikenikäisille. Soitamme ystävällesi, koska häntä odottaa taksi, jota hän ei tilannut... Haluatko kuulla hänen reaktionsa?",
    "enabled_green" : true,
    "order" : 12,
    "order_yellow" : 12,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaTaxi.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 12,
    "order_blue" : 12
  },
  {
    "order_grey" : 13,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploTeroAuteroReservaCancelada.mp3",
    "order_red" : 13,
    "titulo" : "Peruuntunut varaus",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/ReservaCanceladaJuasapp.jpg",
    "enabled_blue" : true,
    "_id" : "3606",
    "desc" : "Sallittu kaikille. Soitamme ystävällesi ravintolasta, because hän halusi peruuttaa varauksensa ilman eri varoitusta. Se on todella törkeää.",
    "enabled_green" : true,
    "order" : 13,
    "order_yellow" : 13,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaTeroAuteroReservaCancelada.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 13,
    "order_blue" : 13
  },
  {
    "order_grey" : 15,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/SE_Ejemplo_Luz2.mp3",
    "order_red" : 15,
    "titulo" : "Blackouten",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/LuzSWE.jpg",
    "enabled_blue" : true,
    "_id" : "3596",
    "desc" : "Lämplig för alla åldrar. Vi ringer din vän eftersom han/hon har fifflat med elförsörjningen och vi tänker avbryta hennes/hans strömförsörjning. Han/hon måste betala för att saker skall fungera!",
    "enabled_green" : true,
    "order" : 14,
    "order_yellow" : 15,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "SE_Luz2.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 15,
    "order_blue" : 15
  },
  {
    "order_grey" : 16,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/SEEjemploLennartMarihuana.mp3",
    "order_red" : 16,
    "titulo" : "Det luktar cannabis!",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/MarihuanaSWE.jpg",
    "enabled_blue" : true,
    "_id" : "3599",
    "desc" : "Det luktar cannabis. För alla åldrar. Vi ringer till din vän eftersom det stinker cannabis i trapporna och grannarna klagar ... Vill du höra vad han har att säga?",
    "enabled_green" : true,
    "order" : 15,
    "order_yellow" : 16,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "SEBromaLennartMarihuana.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 16,
    "order_blue" : 16
  },
  {
    "order_grey" : 14,
    "example" : "https://static.appha.es/mdbfs/bromapp/pub/FIEjemploTeroAuteroVuelo.mp3",
    "order_red" : 14,
    "titulo" : "Muutoksia lentomatkaasi",
    "image_url" : "https://static.appha.es/mdbfs/bromapp/pub/VueloJuasapp.jpg",
    "enabled_blue" : true,
    "_id" : "3604",
    "desc" : "Onko ystäväsi lähdössä lähiaikoina lentomatkalle? Mepä teemme pieniä muutoksia varaukseen pientä korvausta vastaan... katsotaanpa mitä mieltä olet!",
    "enabled_green" : true,
    "order" : 16,
    "order_yellow" : 14,
    "enabled" : true,
    "enabled_yellow" : true,
    "hits" : 0,
    "audiofile" : "FIBromaTeroAuteroVuelo.wav",
    "enabled_red" : true,
    "enabled_grey" : true,
    "order_green" : 14,
    "order_blue" : 14
  }
];

export const LANGUAGE_LIST = [
  { "_id": "fi", "tname": "🇫🇮 Suomi" },
  { "_id": "es", "tname": "🇪🇸 Español - España" },
  { "_id": "gb", "tname": "🇬🇧 English - United Kingdom" },
  { "_id": "us", "tname": "🇺🇸 English - United States" },
  { "_id": "fr", "tname": "🇫🇷 Français - France" },
  { "_id": "de", "tname": "🇩🇪 Deutsch" },
  { "_id": "it", "tname": "🇮🇹 Italiano" },
  { "_id": "pl", "tname": "🇵🇱 Polska" },
  { "_id": "tr", "tname": "🇹🇷 Türkiye" }
];
